### ISSUE TITLE
subrepo init broken?

### ISSUE THREAD

**Issue by nevsan** [ingydotnet/git-subrepo#122]
Maybe I don't understand how I'm supposed to use `git subrepo init`, but I tried the following:

1. Run `git subrepo init <subdir> -r <myremote> -b master` from within an existing repository. This creates a new commit that simply adds the `<subdir>/.gitrepo` file.
2. Run `git bare --init` on a repo at the location `<myremote>`.
3. Run `git subrepo push <subdir>`.
4. Wonder why I got the error `git-subrepo: Can't find a common ancestor between refs/subrepo/<subdir>/fetch and subrepo-push/<subdir>. This might be the case if someone used push --force on the subrepo. You need to find out why and possibly reclone the subrepo.`

I notice that the remote repository does in fact receive the push (it appears in the history of the bare repository). It just seems that I can't push or pull from the repository once it has been created this way. I've confirmed that another fresh project can subrepo clone it and successfully push and pull to the remote--it's only the repo from which I initially ran subrepo init that I cannot push or pull.

I've traced the problem down to `subrepo:merge-base` and `subrepo:branch`. When doing a subrepo push or pull, it looks for a /unique/ merge-base. Note that `subrepo init` created a commit that only added the `.gitrepo` file. However, `subrepo:branch` will delete this file when generating the shadow history. Therefore, you will end up with two commits that have the same tree hash (the commit created by `git subrepo init` and that commit's parent). `subrepo:merge-base` notices that there are multiple candidates and complains, causing `subrepo:push/pull` to fail.

I've only gotten started trying to use this tool, so I don't know what the right solution is here. Perhaps `subrepo:merge-base` should check for this case explicitly, ignoring any commits that have the `git-subrepo init` metadata.

**Comment by grimmySwe** [comment]
Hi Nevada

In step 2 I assume that you intend to `git init --bare`, because I don't have the `git bare` command ;-)

And yes, you seem to have found an issue here and pinpointed the problem. I tested myself and as you say it looks like when you use `git subrepo init` you will get a duplicate commit from a tree hash perspective and that will make merge-base go crazy.

I looked at you suggested patch and it will solve this specific case, but I stumbled on another case where I accidentally updated only the .gitrepo in another commit and this will cause the same problem. 

When I look at the result created by `git subrepo branch` I see that commits only changing the .gitrepo file is still present and that is strange.

I need to investigate some more, but main main thesis right now would be to clean the log so that only commits actually changing stuff in the subrepo should be present.

A side note is that I tried the `git subrepo push --force <subrepo>` and that failed as well, in this case I would think it should work, but I'll look into the main problem first.

**Comment by grimmySwe** [comment]
I think I found a solution to issue when there are "empty" commits.

Using `--prune-empty` in the `git filter-branch`will do the trick. I will create a solution proposal so that you can verify on your end.

**Comment by grimmySwe** [comment]
I have create a branch `issue/122`, please test it and see if it solves your problem.

**Comment by nevsan** [comment]
Your branch works on my end. Thanks!

**Comment by ingydotnet** [comment]
Fixed by #122
