### ISSUE TITLE
How to completely remove subrepo effects in order to begin again?

### ISSUE THREAD

**Issue by robe070** [ingydotnet/git-subrepo#143]
I did a git subrepo init without the remote and git subrepo push with the remote and it seemed to cause the entire repo to be pushed, and not just the subrepo directory. And it may not have been just that sequence which confused it. I issued many subrepo commands.
 
So I was wondering how you ensure that all subrepo state is completely removed – beyond git subrepo clean –all –force and delete the .gitsubrepo file.
 
Or is that absolutely all that is required to ensure there is no residue? Back to the state before the git subrepo init?
 
On a much smaller repo I performed the git subrepo init with remote specified and git subrepo push and it worked a treat.

I retried the original repo too, from a copy of its original state, and that worked fine.

**Comment by grimmySwe** [comment]
git-subrepo will create the .gitrepo file, that is the only visible evidence. There can be some extra branches as well, but they should be removed with the `git subrepo clean` command.

git-subrepo in itself doesn't store/change anything else in your repo.

**Comment by ingydotnet** [comment]
When you init all you are adding is one commit to your history. Just run:

  git reset --hard HEAD^

to go back. Of course there are remotes and refs too, and you can get rid of
those with the clean command. You need to do that before the reset because
afterwards subrepo thinks there are no subrepos.

  git subrepo clean subdir
  git reset --hard HEAD^

Closing this issue. I think we can create an issue to clean orphaned subrepos.
