### ISSUE TITLE
Issue/142 testing: subrepo pull output on same subrepo which refuses to sync using master branch

### ISSUE THREAD

**Issue by robe070** [ingydotnet/git-subrepo#158]
I took the #155 scenario which had no differences and so that was presumably the failure, and added two commits to it. It STILL failed! I've updated the gist in case its useful:
[Session which fails](https://gist.github.com/robe070/6332bc749a267c3c5a57)

So I took branch `issue/142` and merged in commit 9f2ab877 that is the `master` branch code I was currently using and **it worked**. Result was exactly what I expected. Here is the output from `git subrepo pull`. Lots of errors reported. Is this to be expected?
[Session which succeeds](https://gist.github.com/robe070/59fb78f152556b6bc2b9)

Does the `Issue/142' result inform us about why it failed using commit 9f2ab877?

So two questions:

1. Are the `Issue/142` errors expected
2. Can we work out why the `master` code failed?

And it took about 6.5 mins to succeed as opposed to about 4.5 mins to fail :wink:

**Comment by grimmySwe** [comment]
Thanks for testing this, I will look into this when I find the time.

I am currently working on fixing the unittest cases (Pushed work in progress: 073b7be, note that some still fail.)

**Comment by grimmySwe** [comment]
> I took the #155 scenario which had no differences and so that was presumably the failure, and added two commits to it. It STILL failed! I've updated the gist in case its useful: Session which fails
> Can we work out why the master code failed?

Adding new commits will not fix this, as there is only one commit on the target side and the corresponding tree hash exists several times in the source. The only way to solve this would be to revert changes on source so that you don't have duplicates. But I don't know if that is a good option.

> Are the Issue/142 errors expected
issue/142 is work in progress, I pushed in some improvements that I did last night but I don't know if it will solve this problem. I need to sit down and evaluate the outcome. On Issue/142 I have merged in latest master as well.

I am currently assigned to other tasks at work and there are some upcoming events for the evenings so I can't promise any progress in the upcoming days.

**Comment by waynix** [comment]
> But I don't know if that is a good option.

That is not an option!
All projects that use feature branches, will have duplicate tree hashes on the master branch because the **--no-ff** option generates them.

EXAMPLE:
If one executes this code in this [gist](https://gist.github.com/waynix/76b29efc2159be0856d4317487a2a6a2) subrepo will stop to pull, and report this error message:
git-subrepo: Can't find a common ancestor between refs/subrepo/sub/fetch and subrepo/sub. This might be the case if someone used push --force on the subrepo. You need to find out why and possibly reclone the subrepo.

Even your own Project has a duplicate tree hash
`git diff 058bf083e14430ee4e917e503da5401a0e82ae89 618d8bf559a3e678c674d1d8c29fdbc786ed6fec`

PS: git-revert will generate duplicate tree hashes too.

**Comment by ibukanov** [comment]
I also hit the issue. I have a directory where I previously used git-stree tool. I switched to subrepo via first committing a rename, then using subrepo clone then deleting the rename. Now subrepo push generates an error even if there is nothing to push.

**Comment by waynix** [comment]
@ibukanov  have tried the [branch issue142](https://github.com/ingydotnet/git-subrepo/tree/issue/142)
That branch has fixed my test cases.

**Comment by grimmySwe** [comment]
I am closing this issue, please report new issues if you continue testing issue/142 branch.
