### ISSUE TITLE
Import subrepo?

### ISSUE THREAD

**Issue by skevy** [ingydotnet/git-subrepo#176]
Hey -

I've done a lot of research on managing a monorepo with Git, and after trying out subtree's, stree, etc etc etc, I've landed on git-subrepo as my solution. It's really a fantastic project, and is the best way I can see to manage multiple repositories within a single repo.

My team is in the process of migrating to a monorepo with about 15 different projects within it. Some of these projects are OSS (and thus, will remain "subrepos"), but others are private GitHub repos. Right now, git-subrepo is perfect for that use case -- we need to be able to make changes in our monorepo and sync them back out to the private Github repos while people are still working in both places. But eventually, we'd like to move these private Github repos completely within the monorepo. So I was wondering if you guys were considering adding a "git subrepo import" or something of that nature...where we could merge in the repo and retain history. This command could make it so it wasn't ACTUALLY a subrepo (until you did a `git subrepo init` again, if you wanted to).

Would this be something that you would consider adding? Or should this use case be relegated to manually using git commands?

Thanks,
-Adam

**Comment by grimmySwe** [comment]
Do I understand this correctly:
You have a repo foo, that has a subrepo bar inside. You want to import bar into foo, so that there is no subrepo, only a foo repo.

The functionality you are requesting is to somehow get the actual commits from the subrepo bar to appear inside the foo. Currently you could simply remove the .gitrepo file and that would leave you with the correct state but you would miss the actual commits.

I would say that step one would be for you to make this happen with git commands and then when you have found a way share it with us and see if it can be incorporated into subrepo as a import command.
