### ISSUE TITLE
Bug: "git subrepo pull" will crash on a reference to a commit in a subrepo origin with duplicate tree hash in the remote 

### ISSUE THREAD

**Issue by waynix** [ingydotnet/git-subrepo#180]
The plumbing command uses a tree hash to lookup the source commit.
This does not work because all projects that use feature branches or pull requests, will have duplicate tree hashes specialy in the master branch because the **--no-ff** option generates them.
I found this bug because i wanted to pull a new version of googletest into my repo.

EXAMPLE:
If one executes the code in this [test](https://gist.github.com/waynix/76b29efc2159be0856d4317487a2a6a2), subrepo will stop to pull, and report this error message:
`git-subrepo: Can't find a common ancestor between refs/subrepo/sub/fetch and subrepo/sub. This might be the case if someone used push --force on the subrepo. You need to find out why and possibly reclone the subrepo.`

Even this project has a duplicate tree hash
`git diff 058bf083e14430ee4e917e503da5401a0e82ae89 618d8bf559a3e678c674d1d8c29fdbc786ed6fec`

PS: [git-revert](https://gist.github.com/waynix/59baedf8071eea2bfaa2ce8a04fecb20) will generate duplicate tree hashes too.

**Comment by grimmySwe** [comment]
Yes, there are some weak spots with the current tree hash implementation. That's why I have experimented in #142 with redoing it (again...), there has been a lot of other stuff last weeks so I haven't found the time to finish it completely. But if you have some spare time it would be appreciated if you would give the branch "issue/142" a spin and see what you think.

**Comment by waynix** [comment]
Branch "issue/142" seems to fix the issue for me.
I just had to add a commit in my test.

**Comment by grimmySwe** [comment]
Fix for this has reached master.
