### ISSUE TITLE
How to checkout remote branch

### ISSUE THREAD

**Issue by dmoss18** [ingydotnet/git-subrepo#184]
If I have a subtree for a remote with branches `master` and `otherbranch`, is there any way to alternate between those in my local project (the one that cloned the subrepo)? 

Looks like `git subrepo pull <subrepo-dir> -b otherbranch` will pull any new files in and create a commit, but then running `git subrepo pull <subrepo-dir> -b master` doesn't remove those new files, and it creates another commit. Is this not something that can be done?

**Comment by grimmySwe** [comment]
As you say, when you pull in changes it will create a new commit in your parent repo, that commit is not connected to where it came from. So when you pull from another branch, previous pulls will be treated as "regular" changes.

If you want to switch between different subrepo states you can use clone as that will give you the exact state of a subrepo. Pull will consider your local changes.

**Comment by perlpunk** [comment]
Maybe this should become an FAQ, as I've seen similar questions, and I've also been wondering about how to do that.

**Comment by dmoss18** [comment]
What would be the command for cloning? Right now I'm going `git subrepo clone -b <mybranchname> <remote-repo-url> lib` but I'm getting the message `The subdir 'lib' exists and it not empty.`

**Comment by bagza** [comment]
@dmoss18 I guess, it's meant to be recloning or keeping separate clones in different folders. In other words, "one does not simply switch branches with subrepo".

This really needs some clarifications in tutorial/README/wiki.
I'd be happy, if someone would introduce best practices for usage `git-subrepo`.

For example, you have forked project B and want to fix it and clone it to the project A. As I understood, one should have a branch in B, that will be never switched in project A. So, you play around with branches in another clone of lib and then merge all needed changes in the subrepo-tracked branch.

**Comment by perlpunk** [comment]
@dmoss18 For recloning, this worked for me:
```
git subrepo clean subdir
git rm -r subdir
git subrepo clone ...
```

**Comment by pthom** [comment]
Hi,

I am evaluating git-subrepo and I like it very much, and I appreciate the reactivity of the community.
The project I am working on is composed on more than 15 subrepositories, some of these sub-repositories are third partiess, and some of them are internal code for separate modules. Git-subrepo seems to handle it well. 

As far as I understood the way to switch  asubrepo to another branch is to : 
    i. have an additional checkout of the subrepo in a totally separate location
    ii. Create a branch there
    iii. (to be confirmed) git subrepo pull this branch + edit the .gitrepo file

  I would like to be able create and use branches in the subrepositories, and to do it if possible without having to checkout an additional copy of the sub-repo. Would that be possible, or is it totally out of the scope of the project ? 

So, I have one additional question : I would like to be able create and use branches in the subrepositories, and to do it if possible without having to checkout an additional copy of the sub-repo. Would that be possible, or is it out of the scope of the project ?

**Comment by meireles** [comment]
Hi all -- Is there an update regarding this question / feature? I too would love to be able to checkout branches of a subrepo!
I'm temped to use @perlpunk 's approach of re-cloning every time I switch subrepo branches, maybe squashing consecutive commits from simply switching branches.
Any thoughts / directions?

**Comment by grimmySwe** [comment]
I would say that re-clone is the way to go. subrepo clone will give you an exact copy of the branch. And there is a --force/-f flag so that you don't get the
`git-subrepo: The subdir 'bar' exists and is not empty.` message.

Note though that all your local work not pushed to the subrepo will only exist in your parent repo.

**Comment by grimmySwe** [comment]
@dmoss18 Do you consider this issue closed or do you need something more/else?

**Comment by mzenkar** [comment]
I know this is really old, but I'm using subrepo v 0.4.4 and I wanted to switch to a branch of the subrepo since my original clone was tracking the master branch, and I wanted to isolate changes from master while myself and my colleagues implement a new feature.

I tried subrepo clone with --force and --branch= options, but all that did was give me exactly what I had with the .gitrepo clearly indicating that the tracked branch was still master

So what I did was follow what @perlpunk did; however, when I did the clone after that, there was still files that had been built by my changes in the subrepo dir, and even with --force in the clone, the clone failed. I had to manually delete the subrepo dir which did not result in any changes that needed to be committed in the host repository. Finally, I was able to run git subrepo clone again specifying the remote branch and now the .gitrepo file indicates it is tracking the branch that I want to track.

I get the issues involved in switching branches on the subrepo, however, in my case, I had merged in all my changes in the subrepo's repository into the branch I wanted to track - which, I think, would have eliminated any possible tracking errors since the branch and master were on the HEAD.

IMO, there has got to be an easier way to manage branches in a subrepo.
