### ISSUE TITLE
git-subrepo/share/enable-completion.sh: File name too long

### ISSUE THREAD

**Issue by kristiandelay** [ingydotnet/git-subrepo#196]
when running source ~/.bash_profile same with source ~/.bashrc
/Users/kristiandelay/git-subrepo/share/enable-completion.sh: File name too long

both files have the following line:
source /Users/kristiandelay/git-subrepo/.rc
i have tried this line in both files together and alone both throw the above error when running the source command.

just typing  the following in terminal generates this error
$ git subrepo
$ /Applications/Xcode.app/Contents/Developer/usr/libexec/git-core/git-subrepo: line 25: /Applications/Xcode.app/Contents/Developer/usr/libexec/git-core/../ext/bashplus/lib/bash+.bash: No such file or directory

**VERSION INFO**
$ bash --version
GNU bash, version 4.3.42(1)-release (x86_64-apple-darwin15.0.0)
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later http://gnu.org/licenses/gpl.html

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

$ git --version
git version 2.7.4 (Apple Git-66)

$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.11.1
BuildVersion:   15B42

**Comment by grimmySwe** [comment]
Disclaimer, I haven't used MacOS... So I don't know if this helps, but until someone with better MacOS knowledge enters the discussion:

Note: MacOS seems to have a limit for 255 chars per part and maybe an upper limit of the entire path on something like 1024. So that shouldn't be the problem or...

> /Applications/Xcode.app/Contents/Developer/usr/libexec/git-core/git-subrepo

Have you added a link or something here? Or why is there a git-subrepo file here? From the first examples you seem to have the git-subrepo in /users/kristiandelay/git-subrepo or?

Do you have a standalone git installed? or is it part of the Xcode? If it's part of the Xcode, what happens if you install a standalone git?

**Comment by grimmySwe** [comment]
@kristiandelay please reopen and add more information.
