### ISSUE TITLE
Pull Request Workflow?

### ISSUE THREAD

**Issue by dkpalmer** [ingydotnet/git-subrepo#197]
I started off the day planning on refactoring some code and moving to submodules. I then found subtrees and ultimately came upon subrepo. I'm now optimistic that this will satisfy my desire to effectively share some code between projects while minimizing overhead and complexity in doing so. That said, I'm now reaching for the recommended/ideal process for using this working between multiple branches and projects.

I have two projects that have some duplicated code between them. I've setup my subrepo w/ a couple shared files. I cloned into one of my projects and updated the respective imports. Code in our master branch can only be pulled in (no direct push).

Next I branched off in my project and made a commit that modified a project file and a subrepo file. I pushed to the project, iterated through a pull request, and eventually merged. At that point to get things in sync everywhere, I still would need to push to my subrepo and pull-request the resulting 'git subrepo pull' commit to my project. I'm also subject to merge conflicts in my subrepo here after having pushed to my project first.

The additional steps needed here are unfortunate, but during development I get to focus on my project changes and in the end my subrepo-specific changes are magically broken out w/ understandable history in both the project and subrepo. I could iterate and get code updated in my subrepo first, but at that point I almost feel like I might as well just handle my subrepo as an external artifact.

Does anyone have any other suggested workflows they follow for working between multiple projects and making changes through PR's?

**Comment by dkpalmer** [comment]
Bump. Would love your perspective, @grimmySwe. Please let me know if I can clarify the problem any.

**Comment by grimmySwe** [comment]
@dkpalmer  Ok, lets see if I understand the situation correctly:
1. You have several projects/repos (A,B...)
2. You have created a repository with shared code (S)
3. In all of A,B,S master is pull only (no direct push)

So when you work on A you have a dev_a branch and probably create dev_a in S as well?
When you are done you need to create pull requests in both A and S?

Due to the nature of git-subrepo you could ignore it on feature branches and treat it as regular code, then when you want to sync you do that. Did you understand that? ... Lets see if I can give you an example:
Create a feature_a branch in A, do all sorts of changes (including changing in the subrepo code), merge it to master (by pull request or some other way). When you want to share the subrepo you create a sync_subrepo branch in A, pull in latest change, push you merged stuff to the subrepo upstream where you merge it into master (by pull request or some other way), then you can clone in latest subrepo master in your sync_subrepo and merge back to the A master.

Did that help you or have I completely misunderstood you :-)

**Comment by dkpalmer** [comment]
:D OK, I think that helps. Just to clarify a bit more..

As far as our situation:
(1 & 2) Yes
(3) A & B are definitely pull-only. S is pending the findings here.

I haven't done any feature branching (e.g. dev_a) in S. This part is still lost on me (see below).

> then when you want to sync you do that. Did you understand that?

Yes, got it. This has been the best part of git-subrepo for us.

> push you merged stuff to the subrepo upstream where you merge it into master (by pull request or some other way)

I think here we're leaning towards allowing push to the subrepo if it's in sync to avoid a PR cycle nightmare (first repo to sync and push wins). However, can you give an example of how this would work for a pull request, particularly how subrepo feature branching can be executed?

> then you can clone in latest subrepo master in your sync_subrepo

Are you referring to re-cloning the subrepo? Is this better than pulling in the latest code for subrepo master?

**Comment by dkpalmer** [comment]
Interesting on recloning. In the back of my mind I've been worried about getting my subrepo branch in a weird state. Sounds like (clone --force) is an easy recovery.

The example of the subrepo new_branch helps a lot. I wasn't sure if I would need to create a subrepo branch from within A first before it could be pushed to S. I'll look for an opportunity to give this a shot and compare against direct pushes to S (first repo to sync and push wins). I believe the latter will win since it avoids 1 extra PR and put the onus on development from within A & B.

Thanks so much for the clarification.

**Comment by grimmySwe** [comment]
Please let us know what you decided on, it might be useful for other users.

Closing this for now.
