### ISSUE TITLE
Add To Git?

### ISSUE THREAD

**Issue by gamename** [ingydotnet/git-subrepo#199]
Hi,

Do you guys have any plans to add this utility to Git permanently -- maybe in contrib?

TIA,
-T

**Comment by grimmySwe** [comment]
I don't know the process of actually doing that so I can't really answer your question. I do hope though that git-subrepo becomes widely used.

@ingydotnet What do you think of this?

**Comment by Innovative-Ideas** [comment]
@grimmySwe  @ingydotnet 

If you look at: https://github.com/git/git
It says:

> ... Please follow Documentation/SubmittingPatches procedure for any of your improvements.

Here's a link to Documentation/SubmittingPatches:
https://github.com/git/git/blob/5fe494c54ae44ae01a8efa91d00ac9d4c1c475e9/Documentation/SubmittingPatches

Best Regards!

**Comment by ingydotnet** [comment]
My stance has always been to NOT add this to git. That would mean that different versions of git-subrepo would ship with different versions of git, and I'm not comfortable with that. Since the tool only applies to project authors (and certain collaborators) I feel that installing and updating it separately is not a big ask, and furthermore it will allow us to make sure it is never broken on any version of git.

**Comment by Innovative-Ideas** [comment]
Thanks for the response ingydotnet.  
@ingydotnet  @grimmySwe  @gamename  What do you think the benefits would be of adding subrepo to the official git distribution?
