### ISSUE TITLE
Existing file structure and unexpected things

### ISSUE THREAD

**Issue by ryanhelms** [ingydotnet/git-subrepo#208]
Hello, 

I may be an edge case here, I am new to your subrepo idea but think it is fantastic, if I can get it to work for my use case, so here goes

I have an existing file structure that looks like this:

**This is the root Git repository**

![Root Git Repository](https://cloud.githubusercontent.com/assets/1596639/16991418/85bd930c-4e69-11e6-96eb-2f94942a7718.PNG)

**These are the first set of subrepos. They are the application domains (Projects directory above).**

![Application Domain Repositories](https://cloud.githubusercontent.com/assets/1596639/16991470/ab055ea6-4e69-11e6-99e5-0be00bfcdbeb.PNG)

**This is an example of an application domain folder (Acquisitions Domain directory above) , where each project will also be a subrepo.**

![Domain Projects](https://cloud.githubusercontent.com/assets/1596639/16991534/d442d406-4e69-11e6-93cd-8752467a6da5.PNG)

**Current Situation**
- Company is converting to BitBucket for source control server
- I have an existing structure, shown above
- I want to make the root a git repository
- I want to make the application domains into their own subrepos.
- I want to make the domain projects into their own sub-subrepos.  

**Current Issues**

I have the root repository created, pretty standard. Then I move to the next level, Projects. 

That brings up my first question, can I have the root repository use an indirect child (second level) as a subrepo or does each sub-directory in between have to be a subrepo?

I wrote a client application to help me with the conversion, it basically does the following:

**NOTE: Subrepo commands below are pseudo, expect that the commands run successfully**
- Initialize the Root repository
- Initialize the Projects subrepo
- Loop through each Application Domain
  - If it isn't a subrepo, git subrepo init
    **We do not get to this step yet
  - Loop through each Domain Project
  -  If it isn't a subrepo, git subrepo init && git subrepo push
    *\* End **
-  git subrepo push Projects

At the point of the push above, the following happens:
- Entire root is deleted
- In the root folder, the Application Domains are all downloaded, then deleted
- In the root folder, the structure is re-downloded in the correct directory structure
- .gitrepo is added to the Projects folder

I would not expect, with a "subrepo init" for any files to ever be deleted. My expectation would be that a .gitrepo is added to the folder, changes are staged and waiting on my "subrepo push Projects" command.

This should be enough information to get a conversation going. If you can help me through this, I'd love to use subrepos. They fit the bill for everything that I am looking for.

Much appreciated,
Ryan

**Comment by AndrewSmart** [comment]
I don't understand your terminology. You can nest subrepos if that is what you're asking, but you're asking more than that? This sounds more like consulting questions than an issue. Send an email to Ingy if you're still hung up.

**Comment by grimmySwe** [comment]
First of all I would like to clarify that git subrepo is a way to share common things between different repos. So before you start making everything into separate subrepos I would take a moment and really make sure that you intend to share everything.

Why? Because the subrepo will introduce an overhead and if you don't use the benefits of the subrepo it's unnecessary to pay the price.

Don't neglect the proven road of creating subrepos when you actually need them.

You can have indirect childs as subrepos. Look at the git-subrepo repo as an example, it has two internal subrepos in ext/bashplus and ext/test-more-bash.

In #150 there is a discussion on allowing subrepo operations to be performed in a temporary directory. Current situation is that when you perform subrepo operations you will replace the working dir with a temporary copy of the subrepo and then back.

Is that enough to answer your questions? Please let us know if we can help you with anything.

**Comment by grimmySwe** [comment]
@ryanhelms closing this, please reopen and add some more information if you need help.
