### ISSUE TITLE
Ability to clone a certain commit

### ISSUE THREAD

**Issue by dbakker** [ingydotnet/git-subrepo#22]
Since clones in `git-subrepo` are shallow by default, it seems like there is no way to specify any commit other than ones pointed to by branches.

Would you consider adding this feature or suggesting a workaround?

**Comment by ingydotnet** [comment]
I was just playing around with this and was about to tell you that the reason
you can't:

    git subrepo clone <url> -b 2bb1c92

was because Git won't fetch anything but branches and tags for a refspec. It
turns out I was wrong:

    git subrepo clone .git -b 2bb1c92162d4b170661937840fc7b83b069644b3

does work. Git will fetch a full sha1, evidently. Note: you can also give `-b`
a tag.

The bigger issue here, is that you won't be able to push or pull if you decide
to do this. It wouldn't make any sense. Subrepo keeps track of the remote and
the "branch" and here the branch is a sha1 that can/will never change.

I'd like to ask your use case?

Sorry about the late reply. I'm just getting back into this, and an close to
being done with a major refactoring, that should make this a really solid tool.

**Comment by dbakker** [comment]
> I'd like to ask your use case?

Sometimes the tip of the master branch is buggy (e.g. with a Vim plugin that's in development), so I'd prefer using an earlier commit. Then you could pull after the bugs have been fixed (or revert if they haven't).

Recently I switched to using [bower](http://bower.io/) and [peru](https://github.com/buildinspace/peru) and those seem to be a better fit for my use case: Just "pulling" others code & assets from a wide variety of sources without pushing back anything.

Thanks for replying and feel free to close this issue!

**Comment by ingydotnet** [comment]
Thanks. Closing.

**Comment by johnb003** [comment]
Damn, I wanted to do this...

I want to clone -b v2.1 (but at a previous sha)

The reason is we originally had this old sha, and I wanted to pull this commit, apply our changes, and then pull to head afterwards, to merge in upstream changes.

**Comment by grimmySwe** [comment]
@johnb003 You can always work in the subrepo space, then you can do anything you want as long as git allows it.

**Comment by johnb003** [comment]
FYI, I got this to work by using git repo to pull master, and then hand-editing the .gitrepo, commit message, and refs to force them to the hash I wanted them to (and overwrote the source with the source at that hash as well.

Then I was able to apply our code (which diverged in a separate commit), and then pull to head.

At first I wasn't able to get it to work, and thought I missed something, but it turned out, once I switched to 0.4.0 it worked, and I accomplished my goal that way.
