### ISSUE TITLE
On pull I get => git-subrepo: Command failed: 'git branch ...'

### ISSUE THREAD

**Issue by jamiechong** [ingydotnet/git-subrepo#222]
I have a subrepo inside another subrepo. 

```
subrepo/site                          https://github.com/roots/bedrock.git
subrepo/site/web/app/themes/mytheme   https://github.com/roots/sage.git
subrepo/trellis                       https://github.com/roots/trellis.git
```

I was able to `git subrepo pull` with `git-subrepo#master` for `trellis`
I had to use branch `issue/142` to pull for `site` because of ticket #215 

But the pull fails for `site/web/app/themes/mytheme` on both `master` and `issue/142`

On `master` I get this error: 
`git-subrepo: Command failed: 'git branch subrepo/site/web/app/themes/mytheme'.`

On `issue/142` I get this error:
`git-subrepo: Command failed: 'git checkout -B subrepo/site/web/app/themes/mytheme 2c191bca0dbeec31c41b96020e76198dad45e891'.`

It seems like the same error to me. 

What else can I do to debug this?

**Comment by grimmySwe** [comment]
Hi, there is a verbose (-v) and a debug (-d) flag that can be used with subrepo. Adding both of those flags will output a lot of useful information.

**Comment by grimmySwe** [comment]
I see that you have subrepo within subrepo:
subrepo/site                                             https://github.com/roots/bedrock.git
subrepo/site/web/app/themes/mytheme   https://github.com/roots/sage.git

There might be conflicts in this if you work with the sage repo as active because then you might override the bedrock repo.

If you want sage to be a part of bedrock then I think it would be best to perform that operations withing the bedrock repo.

**Comment by grimmySwe** [comment]
Closing issue, @jamiechong please reopen with more information if you still experience the problem.
