### ISSUE TITLE
Proper protocol for making changes to a subrepo

### ISSUE THREAD

**Issue by animetrics** [ingydotnet/git-subrepo#254]
One thing I feel is missing from the docs (could be wrong) is proper protocol for making changes to a subrepo from within parent repo and pushing (or not pushing) those changes.   It seems that one would do

    1. git add ext/a_sub_repo/file.cpp
    2. git commit -m "made a mod to file.cpp in a_sub_repo"
    3. git push
    4. git subrepo push ext/a_sub_repo

Is this correct?  Opting out of step 4 gives the option of keeping subrepo changes in the parent repo but not pushing to the subrepo remote. 

One other question, how do I tell after step 3 that my subrepo changes haven't been pushed?  I don't seem to get the "your branch is X commits ahead of ...." with any status commands.

**Comment by grimmySwe** [comment]
> Is this correct? Opting out of step 4 gives the option of keeping subrepo changes in the parent repo but not pushing to the subrepo remote.

Step 3. is optional in some sense, when you have commits in your repo (pushed or not) then you can transform the changes and push them to the subrepo.

> One other question, how do I tell after step 3 that my subrepo changes haven't been pushed? I don't seem to get the "your branch is X commits ahead of ...." with any status commands.

There is no quick way to determine this because you need to perform the transformation process first. We have considered adding a --dry-run to the push so that you can #142, #202:
``` 4. git subrepo push --dry-run ext/a_sub_repo ```
and get some kind of status.

right now you need to perform these steps manually by:
```
git subrepo branch --force ext/a_sub_repo
git log --oneline --decorate subrepo/ext/a_sub_repo
```
if the `subrepo/ext/a_subrepo` differs from your `refs/subrepo/ext/a_sub_repo/fetch` then you have local changes. The branch command will transform your local changes into the subrepo "space" and then you use log to determine if the HEAD of that branch differs from the last fetch.

**Comment by animetrics** [comment]
Thanks @grimmySwe 

> Is this correct? Opting out of step 4 gives the option of keeping subrepo changes in the parent repo but not pushing to the subrepo remote.
> 
> > Step 3. is optional in some sense, when you have commits in your repo (pushed or not) then you can transform the changes and push them to the subrepo.

What is meant by "transform" exactly?  Is that just `git subrepo push ext/a_sub_repo`? So if were to swap steps 3 and 4, nothing would happen when I run step 4 (assuming all my commits were suprepo commits)?

**Comment by grimmySwe** [comment]
Transforming them into the subrepo space so that your changes can be pushed
to the subrepo.

Pushing to the subrepo has no impact on your regular repo. There you work
as you normally do. Switching 3 and 4 makes no difference but might even be
a good thing because you will get possible subrepo conflicts first and can
include the solution in your push to the normal repo. Otherwise you might
need to push again.
fre 17 feb. 2017 kl. 22:04 skrev animetrics <notifications@github.com>:
