### ISSUE TITLE
Pushing tags

### ISSUE THREAD

**Issue by varac** [ingydotnet/git-subrepo#258]
Hi, 

I'm not sure if this is a feature req. or a documentation issue. But one thing that fell on my toes recently was that I needed to change my workflow of pushing tags.
Before, I used a superproject with submodules, and only had tags that belonged to my superproject. So I used `git push --tags` to synchronize my local tags with the remote.

I realized with subrepos, tags from all subrepos will present, and using `git push --tags` will result in a superproject tagged with tags from its subrepos.
This is a weird behaviour, maybe intended so I'd like you to confirm is this is how things are and document this potential issue or a workaround.

**Comment by grimmySwe** [comment]
Having read your question a little bit more carefully I don't think there should be any problem. Tags from subrepos should stay in their repos. I say should because that was my view of how it worked. 

Reality seems a little different though:
@ingydotnet I noticed that in subrepo:fetch we use `git fetch`without the `--no-tags`, should we add that to prevent subrepo tags to pollute the main repo?

**Comment by varac** [comment]
> @ingydotnet I noticed that in subrepo:fetch we use git fetchwithout the --no-tags, should we add that to prevent subrepo tags to pollute the main repo?

Yes please !

**Comment by ingydotnet** [comment]
Not sure I got everything here, but subrepo tags should not get into the supe, certainly. Make it so.

**Comment by grimmySwe** [comment]
I am testing out this now, but fail to create the error in the first place. I will add '--no-tags' just for safety but it might be that the current construct already prevent tags due to specifying a refspec directly. I have sent a mail to the git mailing list for clarification.

**Comment by anthozep** [comment]
@varac How did you create tags in a subrepo? Using git tag inside a subrepo tags the superrepo for me
