### ISSUE TITLE
How to merge two branches with subrepos?

### ISSUE THREAD

**Issue by ephemerr** [ingydotnet/git-subrepo#278]
I am trying to migrate from submodules, and I am new to subrepo.
I have created by cloning two branches on subrepos, corresponding to two branches on submodules.
Now I am trying to merge and have conflict in .gitrepo files, how should I resolve it?

**Comment by grimmySwe** [comment]
Your options:
1. It might be easier to actually merge the subrepo on it's own, then clone in the result into your main repo.
2. If you merge on main repo level I will recommend that you select one of the sides theirs/ours otherwise you will have a strange state in the subrepo and that might cause confusion up ahead.

Did that make any sense?

If not you probably need to give me a little more example on what you are trying to accomplish.

**Comment by ephemerr** [comment]
Thank you for an answer!

I am trying to merge two branches of project (like devel and master) each having subrepo in diferent state. 
As I could understand your answer I should prepare subrepos before doing git merge <branch>?

**Comment by grimmySwe** [comment]
Well, you can do as normal, but for the actual .gitrepo file it would probably be best if you use one of the, not mixing the content. You will though not get any merge commit in the subrepo that way.

**Comment by ephemerr** [comment]
Does `git subrepo commit` for subrepos afterwards fix situation?

**Comment by grimmySwe** [comment]
What do you mean by fix?

`git subrepo commit` is used after you solved conflicts in the `git subrepo pull`.

**Comment by ephemerr** [comment]
I mean, after merge there would be .gitrepo with some commit information does not corresponding to actual files in working tree. And commit should fix it. 

Thank you for your answers, I think I should get more practice with subrepos, for better understanding it.
