### ISSUE TITLE
issue with "parent" when moving a subrepo under another repository

### ISSUE THREAD

**Issue by Yehonal** [ingydotnet/git-subrepo#395]
Hello

i've an issue with an "edge" case of subrepo usage: i've a boilerplate repository with various subrepo inside.
Everytime we starts a new project we copy such folder and "git init" another repository for new project.

The boilerplate includes a bash script that automatically pull and push changes for all included subprojects using subrepo commands. However the "parent" variable inside .gitrepo is not valid in new repository so we've to change it manually for each repository with a correct sha string.

Is there any way to automatically fix such variable using latest sha commit from current parent branch?

**Comment by grimmySwe** [comment]
@Yehonal You might want to consider using the subrepo clone instead of push/pull, that way you would reset the new content.

**Comment by contentfree** [comment]
@grimmySwe : This is long closed but can you provide some hints on how they'd (and we'd) use subrepo clone in this situation where we have a boilerplate repository that gets (I assume) git archived and unpacked for the new project? We do the same thing and I ran into this issue today where the parent doesn't exist in the new project's git repo so git subrepo push fails (due to `git-subrepo: Command failed: 'git rev-list --reverse --ancestry-path --topo-order ...`)

**Comment by contentfree** [comment]
We really just need a way to do a reclone that _actually_ performs all the steps of the clone. In the case of our boilerplate project (and maybe the same in @Yehonal 's case): We already have the <dir>/.gitrepo file. When `clone --force` is used to "reclone" the subrepo it sees that the .gitrepo file exists and moves on to checking if the subrepo is current (which is usually is) – the parent reference is never updated. (And there's a bit of a chicken and egg problem anyway: A fresh copy of the boilerplate repository likely won't have any commits yet)

**Comment by grimmySwe** [comment]
@contentfree Ok, the git archive will put a big dent in the subrepo logic as it will clean out all references. And as you say the clone will only update if it's not up to date.
Just curious, why are the subrepos included in the boilerplate repo? Wouldn't it be possible to have the boilerplate repo only contain a script for cloning the subrepos? or are the subrepos so large that you want them directly?

**Comment by contentfree** [comment]
We use a boilerplate project for After Effects video projects. We have a separate utility library that we include in the boilerplate project via subrepo. 

What I've taken to is doing the git archive, initializing git in the new project, making an initial local commit (because subrepo doesn't work on a bare repository), using sed to change the parent commit in lib/.gitrepo, and amending the previous commit and finally force-recloning the subrepo. A little wonky but seems to get me to a working state.

**Comment by admorgan** [comment]
@contentfree I believe that the clone --force not updating if it is up to date, but the parent ref is invalid is a bug. An  easy to fix one at that.

**Comment by contentfree** [comment]
@admorgan Did you ever get around to fixing the bug you reference above?

**Comment by admorgan** [comment]
No, I  am still working on it. I was on vacation for a few weeks so that did slow things down.
