### ISSUE TITLE
[Question] Is it possible to ignore files when using repo as a subrepo?

### ISSUE THREAD

**Issue by ychechik** [ingydotnet/git-subrepo#437]
let's say I have a file I need to use when I'm working on the repo as a standalone repo, but not when I use the repo as a subrepo or a subdir in another repo.

Is such a thing possible to do currently?

**Comment by admorgan** [comment]
No, can you give me a use case?

**Comment by YoniChechik** [comment]
@admorgan, for example a pyproject.toml file which is used to initiate a poetry environment (python). One need this file when the repo is a standalone, but will never use this when the repo is a subrepo (subfolder) in a larger project with it own pyproject.toml file in a higher dir level

**Comment by admorgan** [comment]
I believe I understand the use case. More specifically I can see the case for tools like test suites that automatically search for tests to run. I see two problems with adding a feature like this
1. It is hard to describe on from a UX perspective
 a. Remembering what file(s) were removed
 b. Describing in the pulls that significant edits were done
 c. What happens when you create a file locally with the same name as an ignored remote
2. It would significantly slow down subrepo and likely lead to more frequent manual intervention being required

I am happy to look at patches, but this is not a feature I am personally interested in creating.

**Comment by admorgan** [comment]
Do you mind if I close this? If you plan to create patches to support this I would prefer to leave it open.

**Comment by ychechik** [comment]
closing
