### ISSUE TITLE
Why is the subrepo contents staged to the "parent" repo index?

### ISSUE THREAD

**Issue by mcarifio** [ingydotnet/git-subrepo#441]
First, assuming I can come to understand some of the details, git-subrepo is cool, ty for it.

Second, what's the intended relationship between the subrepo and it's "parent"? I think they're independent of each other and one just "sits" underneath another. After a clone operation like
`git subrepo clone gh:mcarifio/emacs-project-build project/build -b dev -f` I get my subdirectory `project/build` and the parent project "knows about" the subrepo. But I also notice that `project/**` is staged as new files for a commit to the parent repo. That seems counter intuitive to me. I don't want to commit a subrepo's files to the parent (do I?).

I would actually think that adding an ignore pattern to the parent's `.git/info/exclude` is the right way to go and you can find the subrepo's with `find` rather than `git ls-files`. But I'm so new to this (like tonight), I might be missing the bigger picture.

Please advise. Thanks.

**Comment by admorgan** [comment]
The pattern you express is similar to how git submodules works, git subrepo is closely related to how git subtree works.

The files for a subrepo reside in the parent repository. It is the only way in git to force everything to be in a consistent state. It also allows for changes that span files in multiple subrepos at once. If you are working in a monorepo this is a wonderful feature.

The required parent link is so that when you push changes up to a subrep, or pull them down, git is able to reproduce a branch that contains only the files associated with the subrepo and perform the desired action accordingly.

You can find the subrepos with find instead of git ls-files, but git ls-files is consistently much, much faster.

**Comment by mcarifio** [comment]
Ah, ty. I'll return to the documentation for another read. But just confirm, the "use case" here is a situation where a subrepo is "shared" across several parents (hence the refactoring out) but both the parent and the sub can be committed by the end user? I could for example copy the subfolder (too many terms, sorry about that) into both parents, but then I have two separate copies that could skew away from each other (correct?).

**Comment by admorgan** [comment]
As I read it you are correct.
