### ISSUE TITLE
Is sparse checkout workflow supported for subrepos?

### ISSUE THREAD

**Issue by RomanValov** [ingydotnet/git-subrepo#551]
I'm considering alternatives for submodules used in my current project and found subrepos overall looks nice.

However I haven't found any mentions whether sparse checkout workflows are supported.

They are crucial for my project because dependency repository occupies >10Gb overall (>400Mb per commit)
and all I need to use in my project is a 50Mb sub-directory. With submodules I can setup sparse checkout, i.e.:

```
$ git clone my-project.git
$ cd my-project
$ git clone --sparse --no-checkout --filter=blob:none dependency.git
$ git -C dependency/ sparse-checkout init --cone
$ git -C dependency/ sparse-checkout set subdir/
$ git submodule add dependency.git dependency/
$ git submodule update --force
```

Not very convenient and I have to re-setup sparse checkout on each clone.
But it works. Is there a way to do a similar sparse checkout using subrepos?

**Comment by admorgan** [comment]
No, subrepo will only include the files used by squash merges, but does not support sparse checkouts because all the content of the subrepo is included in the commit. It prevents the issues with submodules where you have to run git submodule update --init --recursive after every move i the tree.

**Comment by JWCS** [comment]
Counter: I think it works. 
After looking at the src and doing some tests:
``` bash
cd super_repo
git init
# https://stackoverflow.com/a/75264657/
set +H
git sparse-checkout set --no-cone "/*" "!/my_dep/" "/my_dep/.gitrepo" "/my_dep/data_i_want/"
set -H
# cat .git/info/sparse-checkout # can confirm or modify the allow or exclude (!) filters
git subrepo clone <my_dep-remote> my_dep
```
Pushes, pulls, commits, etc seem to Just Work.

**Comment by JWCS** [comment]
(Don't read the rest of this if you're a casual user).

On reducing data pull, RomanValov's initial topic:
Data is retrieved using a git fetch, and I'm uncertain how the git fetch mechanism applies any filters (ex --filter=blob:none). It seems like that would/ought to be set in the initial cloning... 
So if the super_repo is the only "real" repo, perhaps instead of `cd super_repo && git init`, it gets initialized as a `git clone --filter=blob:none <super_repo-remote>`?
What is a little more clear to me is that, however its stored, the only `git fetch` support for partial clones is the mysterious `--refetch` option, which should tell the remote to re-do its refspec/packfile? to whatever the super_repo has saved.
There is some further docs under [git-rev-list --filter=<filter-spec>](https://git-scm.com/docs/git-rev-list#Documentation/git-rev-list.txt---filterltfilter-specgt) that suggest the sparse checkout spec may already be applied, and applied to blobs...
In anycase, if this is a further issue, the answer lies in the git source, but some experimental testing might be possible with the `git rev-list --filter-provided-objects/--filter-print-omitted`

One possible caveat or bug: in my testing, I had, from the same origin, subrepo cloned a test dependency twice; once with no sparse checkout spec for that subdir, once with a sparse checkout spec for the subdir. Most operations were going well, pulls, commits, pushes, etc. 
But there was a curious case, where after some combination of state changes, a further git subrepo pull on the sparse checkout subrepo caused an error in the subrepo:commit function, at the "Put remote subrepo content into <subdir>", on the git call `git read-tree --prefix=<subdir> -u subrepo/<subdir>`.
The error was that `Entry 'subdir/d3/f5' overlaps with 'subdir/d3/f5'. Cannot bind.`
The curious part is that d3/f5 should be excluded by the sparse filter and not in the subdir. I don't think I can call this merely a bug on having two subrepos for the same remote, and trying a pull with --force, given the sparse option, does seem to just break the git-subrepo flow.
