### ISSUE TITLE
Question: Not easy to understand the diff & benefits from git-subtree

### ISSUE THREAD

**Issue by boussou** [ingydotnet/git-subrepo#572]
Not easy to understand the diff & benefits from git-subtree.

Here are the main differences of git-subrepo command compared to git-subtree I can see by reading the introduction:
- there exist a .gitsubrepo file providing source info (only visible to the parent repo)
- so then collaborators know when a subdir is a subrepo (it has a .gitrepo file).
- Different branches can have different subrepos in different states, etc.
- when you pull from the subrepo, it does not keep history
- when you do push from parent to subrepo (git subrepo push shared), it creates a rev to the parent
- when you do push from parent to subrepo, you need to leave the master branch in subrepo
- the  .gitsubrepo file is updated and therefore is part of changes in any rev

Not clear about that 
- Branching with subrepos Just Works: git-subtree too no?
- Moving/renaming/deleting a subrepo subdir JustWorks
- Your git history is kept squeaky clean.: how compared to git-subtree?
- Upstream history (clone/pull) is condensed into a single commit: you can squash in git-subtree (or not)
- Fixes known rebase failures with git-subtree: ??

Even from the tutorial here Basics I can't see significant differences - but I am afraid it would appear later?
https://github.com/ingydotnet/git-subrepo/wiki/Basics

Thanks!

**Comment by admorgan** [comment]
Git subtree is a fine tool that my fit your needs. In my experience it has a lot of issues that does now work with the projects I am associated with. Because there are numerous questions contained in this issue I am going to focus on the things you stated you were having the most difficulty understanding first and have a back and forth until you feel that you have a firm grasp on what is being offered by git-subrepo.

git-subtree has issues with multiple branches having multiple branches with local changes. This is because git keeps a special subtree branch locally and all operations for subtree operate on this branch. Therefore if you are moving between branches that have different local changes I have found that subtree can get in a state that is very difficult to get out of. git-subrepo creates temporary worktrees and replays local commits with the fetched history of the parent repo. This is slower for some operations, but prevents the branching issues.

As for moving/renaming/deleting subrepos https://stackoverflow.com/a/46310507/13673968 does a great job describing the issue with everything except deleting. The issue with deleting is that if you delete a subtree and then re-add a different one to the same space, at least when I used it last, it would sometimes find the original subtree and get confused. I understand that has gotten better over time.

git-subtree does a merge of the parents history into the history of the containing project. That causes the git graph to become messy with at least that merge. This merge is required for git-subtree to know what to pull and push in the future, whereas git-subrepo only supports squash merges which keeps the graph cleaner than git-subtree allows. I believe is also addresses the confusion about the upstream history.

See https://stackoverflow.com/questions/12858199/how-to-rebase-after-git-subtree-add for info about issues with rebasing in git-subtree.

git-subtree and git-subrepo aim to address the same problem, and therefore have far more similarities than differences. One uses git internals to store the metadata and has some tricks to optimize a few expensive operations. git-subrepo addresses some of the limitations discovered in the git-subtree implementation and focuses on keeping the mechanism for solving the problem out of git.

The biggest difference between the two is only a small subset of maintainers of a code base need to have git-subrepo installed, or have any knowledge of git-subrepo at all. git-subtree requires all developers to have the tool installed (conveniently included with git) and may have to interact with the tool which this tool deems unacceptable.

**Comment by boussou** [comment]
FYI,  git-subrepo is used by the Artix Linux distro https://artixlinux.org/.

They have complaints about git-subrepo because they have to clone 3000+ repos for the OS.
The pain point are the long git filter branch calls made by git-subrepo.

But this looks like kind of an extreme use-case, becaude they do that daily. 

(this is just for the record)

**Comment by ychin** [comment]
I just stumbled upon this thread while trying to decide on Git subtree vs subrepo myself as well. Just some of my 2c.

> The biggest difference between the two is only a small subset of maintainers of a code base need to have git-subrepo installed, or have any knowledge of git-subrepo at all. git-subtree requires all developers to have the tool installed (conveniently included with git) and may have to interact with the tool which this tool deems unacceptable.

I don't think this is true unless I'm missing something. Git-subtree knowledge is only necessary for owners/maintainers who need to push to / pull from upstream. This is the same as Git-subrepo. A big point of subtree (either the manual subtree merge method or the git-subtree tool) is that it's convenient for users & collaborators and require no extra steps (same as subrepo), unlike Git submodules.

---

Personally I'm still deciding. I think both subtree and subrepo are good for "git clone and good to go", and allow for a tighter upstream modification loop than submodules. I think git-subtree could benefit from better tooling (e.g. renaming is actually easier than that StackOverflow post implies but lack of native support means you have to know how to do it), and it feels like "use simple tool that retains Git's philosophy, while keeping commit history messier/more complicated" (since it takes advantage of merging branches without a common root which is a somewhat esoteric feature to some folks). Meanwhile git-subrepo is more "use a more complicated tool but results in a cleaner linear commit history".

FWIW I don't find the git-subtree squashed commit history to be *that* messy. If you have a merge-based workflow you should probably get used to doing `git log --first-parent` and only dive in if need be. If you do that you only see one commit per upstream pull, and it's even clearer what is an upstream merge, versus a local change. But I digress. The unrelated branches without common root could sometimes cause issues though.

**Comment by admorgan** [comment]
@ychin there are a lot of opinions about git history, I find most github histories almost impossible to follow because of what I consider poor practices managing pull requests, but this is entirely a personal thing and therefore there is no correct answer.

In response to the section about who needs to know about using subtree vs subrepo. If you make a change with subtree it is expected that those changes will be pushed upstream to the external repos, that means everyone is expected to know how this interaction works. It works less well with newer processes such as github with CI controlling the workflow than when it was originally constructed. Subrepo expects the repo owner to decide when to push changes and makes it easier to only push changes to certain repos and keep local changes on other repos. Functionally they aren't considerably different, it is a point of view thing, but that point of view change has made my interactions better for the projects I am working on.

There is no shade thrown at subtree, it is a good tool that a lot of people depend on, but I find that subrepo aligns with my workflow better. I hope you find a workflow that works well for you also.
